version: 2.1
orbs:
  notify-slack: interstellar/notify-slack@0.2.0
jobs:
  build:
    docker:
    - image: circleci/openjdk:11.0.1-jdk
    working_directory: ~/sample-springboot-api
    steps:
    - checkout
#- setup_remote_docker:
#        docker_layer_caching: true
    - run:
        name: Login to DockerHub
        command: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run: mvn clean package
    - run: mvn clean compile jib:build -Dimage=vinodplank/junacards:$CIRCLE_BUILD_NUM
    - store_artifacts:
        path: target/classes
        destination: sample-springboot-api
workflows:
  version: 2.1
  workflow:
    jobs:
    - build
