version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build:
    docker:
    - image: circleci/openjdk:11.0.1-jdk
    working_directory: ~/sample-springboot-api
    steps:
    - checkout
#- setup_remote_docker:
#        docker_layer_caching: true
    - run: mvn clean package
    - store_artifacts:
        path: target/classes
        destination: sample-springboot-api
    - slack/status:
          fail_only: false
          webhook: $webhook
workflows:
  version: 2.1
  workflow:
    jobs:
    - build
